package com.ghost.model.enums;

public enum AuditAction {
    QUESTION_CREATED,
    QUESTION_EDITED,
    QUESTION_DELETED,
    COMMENT_CREATED,
    COMMENT_EDITED,
    COMMENT_DELETED,
    VERIFIED_ANSWER_PROVIDED,
    QUESTION_CLOSED,
    QUESTION_FORWARDED,
    USER_ENLISTED,
    USER_REMOVED,
    WHITEBOARD_CREATED,
    WHITEBOARD_DELETED,
    REPORT_SUBMITTED,
    CONTENT_HIDDEN,
    CONTENT_RESTORED,
    TOPIC_CREATED,
    TOPIC_DELETED,
    OWNERSHIP_TRANSFERRED
}
