module.exports = {
  preset: 'jest-expo',
  testMatch: ['**/?(*.)+(test).[tj]s?(x)'],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  testPathIgnorePatterns: ['/node_modules/'],
  collectCoverage: true,
  coverageDirectory: '<rootDir>/coverage',
  collectCoverageFrom: [
    '<rootDir>/services/auditLogService.ts',
    '<rootDir>/services/authService.ts',
    '<rootDir>/services/bookmarkService.ts',
    '<rootDir>/services/commentService.ts',
    '<rootDir>/services/notificationService.ts',
    '<rootDir>/services/questionService.ts',
    '<rootDir>/services/reportService.ts',
    '<rootDir>/services/topicService.ts',
    '<rootDir>/services/whiteboardService.ts',
    '<rootDir>/stores/notificationStore.ts',
    '<rootDir>/stores/whiteboardStore.ts',
    '<rootDir>/hooks/useQuestionDetailModel.ts',
    '<rootDir>/utils/authRedirect.ts',
    '<rootDir>/utils/formatDate.ts',
    '<rootDir>/utils/inviteCode.ts',
    '<rootDir>/utils/notificationPayloads.ts',
    '<rootDir>/utils/questionCommentEvents.ts',
    '<rootDir>/utils/questionEvents.ts',
    '<rootDir>/utils/sanitize.ts',
    '<rootDir>/utils/validators.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
};
