module.exports = {
  preset: 'jest-expo',
  testMatch: ['**/?(*.)+(test).[tj]s?(x)'],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  testPathIgnorePatterns: ['/node_modules/'],
  collectCoverage: true,
  coverageDirectory: '<rootDir>/coverage',
  collectCoverageFrom: [
    '<rootDir>/stores/whiteboardStore.ts',
    '<rootDir>/stores/notificationStore.ts',
    '<rootDir>/services/auditLogService.ts',
    '<rootDir>/services/authService.ts',
    '<rootDir>/services/commentService.ts',
    '<rootDir>/services/notificationService.ts',
    '<rootDir>/services/questionService.ts',
    '<rootDir>/services/reportService.ts',
    '<rootDir>/services/whiteboardService.ts',
    '<rootDir>/hooks/useQuestionDetailModel.ts',
    '<rootDir>/utils/formatDate.ts',
    '<rootDir>/utils/inviteCode.ts',
    '<rootDir>/utils/notificationPayloads.ts',
    '<rootDir>/utils/questionCommentEvents.ts',
    '<rootDir>/utils/questionEvents.ts',
    '<rootDir>/utils/sanitize.ts',
    '<rootDir>/components/QuestionCard.tsx',
    '<rootDir>/components/ui/GlassButton.tsx',
    '<rootDir>/components/ui/GlassCard.tsx',
    '<rootDir>/components/ui/GlassInput.tsx',
    '<rootDir>/components/ui/GlassModal.tsx',
  ],
  coverageThreshold: {
    global: {
      branches: 50,
      functions: 52,
      lines: 58,
      statements: 58,
    },
  },
};
